-- TODO. 同一张表: 基于不同的PART存储到不同的分区
-- 1. 每一个PART_ID对于一个分区, 不支持PART_ID数量过大
-- 2. 目的是基于PART_ID高效删除大量数据

CREATE TABLE RECORD_DATA_P (
    ID VARCHAR2(10) NOT NULL,
    PART_ID VARCHAR2(10),
    DATA_CHECKSUM CHAR(64),
    ADDR_CHECKSUM CHAR(64),
    STATUS VARCHAR2(20) NOT NULL
)
PARTITION BY LIST (PART_ID) AUTOMATIC ( -- 使用自动创建的分区名称, 不可控
    PARTITION P_INIT VALUES ('INIT') -- 初始分区名称
);

SELECT TABLE_NAME, PARTITION_NAME, HIGH_VALUE -- 分区字段值
FROM USER_TAB_PARTITIONS
WHERE TABLE_NAME = 'RECORD_DATA_P';

SELECT PARTITION_NAME -- 找到自动生成的分区名称
FROM USER_TAB_PARTITIONS
WHERE TABLE_NAME = 'RECORD_DATA_P' AND HIGH_VALUE LIKE '%A100%';

ALTER TABLE RECORD_DATA_P
DROP PARTITION SYS_P12345 -- 基于特定分区名称来删除，无法根据HIGH_VALUE值删除
UPDATE GLOBAL INDEXES;